title: Sriashwin Sridharan

description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
show_downloads: false
logo: https://github.com/Srriash/srriash.github.io/blob/main/assets/images/Profile.jpeg

social:
  linkedin: sriashwin-sridharan
  github: Srriash

