title: Sriashwin Sridharan

description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
show_downloads: false
logo: https://github.com/Srriash/srriash.github.io/blob/c3fd9296f6353351ba168ccb526a07767c6224df/passport%20size%20photo_small.jpg
# Social Media
social:
  linkedin: sriashwin-sridharan
  github: Srriash

