title: Sriashwin Sridharan
description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
logo: D:\Academic_Weizmann\WIS_pythonGabor\Coding\srriash.github.io\assets\images\profile.jpg
Show_downloads: false

