title: Sriashwin Sridharan
description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
logo: https://github.com/Srriash/srriash.github.io/blob/main/passport%20size%20photo_small.jpg?raw=true
Show_downloads: false

