title: Sriashwin Sridharan
description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
show_downloads: false

# Social Media
social:
  linkedin: sriashwin-sridharan
  github: Srriash

