title: Sriashwin Sridharan
description: Master's Student at the Weizmann Institute of Science
theme: jekyll-theme-minimal
link: [Weizmann profile]("https://www.weizmann.ac.il/pages/search/people?keywords=sriashwin+sridharan&advanced%5Bemail%5D=&advanced%5Boffice_phone%5D=&advanced%5Bdept%5D=&advanced%5Bemptype%5D=&person_id=&op=Search")
show_downloads: false

